services:
  sqlmesh-dbt:
    build:
      context: .
      dockerfile: ./sqlmesh-dbt/Dockerfile
    volumes:
      - ./shared:/shared
    environment:
      DUCKDB_FILE_PATH: /shared/db/datamart.duckdb
    ports:
      - "8000:8000"
  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
      args:
        SUPERSET_ADMIN: ${SUPERSET_ADMIN}
        SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
        SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
        - "8088:8088"
    command:     gunicorn --bind  "0.0.0.0:8088" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
    volumes:
        - ./shared/db:/app/superset_home/db
    depends_on:
      - sqlmesh-dbt